services:
  backend:
    build: 
      context: ./mishmash
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./mishmash
          target: /app
          action: sync
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/*.pyo"
            - "**/*.pyd"
            - "**/.Python"
            - "**/env"
            - "**/venv"
            - "**/.env"
            - "**/.venv"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"  # For development debugging
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,dev-mishmash.colab.duke.edu,mishmash.colab.duke.edu
      - DATABASE_NAME=mishmash
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: ./mishmash/frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./mishmash/frontend/src
          target: /app/src
          action: sync
          ignore:
            - node_modules/
            - build/
        - path: ./mishmash/frontend/public
          target: /app/public
          action: sync
    volumes:
      - ./mishmash/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mishmash
    ports:
      - "3306:3306"  # For development debugging
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  static_volume:
  media_volume:
  build_volume:
