version: '3.8'

services:
  frontend:
    build: 
      context: ./mishmash/frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=/api
    volumes:
      - frontend_build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

  backend:
    build: 
      context: ./mishmash
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,dev-mishmash.colab.duke.edu,mishmash.colab.duke.edu
      - DATABASE_NAME=mishmash
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 4 mishmash.wsgi:application"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/static:ro
      - frontend_build:/app/build:ro
      - media_volume:/app/media:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mishmash
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  static_volume:
  media_volume:
  frontend_build:
  nginx_logs:
