"""
Study Abroad Program API URL Configuration
========================================

This module defines the URL routing for the Study Abroad Program's REST API.
It maps URL patterns to their corresponding views and uses Django REST Framework's
DefaultRouter for automatic URL generation for ViewSets.

Available Endpoints:
------------------
- /api/programs/
    - GET: List all programs
    - POST: Create new program (admin only)
    - /<id>/: Get, update, delete specific program
    - /<id>/application_status/: Get current user's application status

- /api/applications/
    - GET: List user's applications
    - POST: Submit new application
    - /<id>/: Get, update specific application

- /api/login/
    - POST: Authenticate user and get token

- /api/users/me/
    - GET: Get current user's profile

Used by:
--------
- Frontend React components for API communication
- Mobile apps (future) for data access
- Admin interface for program management
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProgramViewSet, ApplicationViewSet, login_view, logout_view, get_current_user

# Initialize the DefaultRouter for automatic URL generation
router = DefaultRouter()

# Register ViewSets with the router
# This automatically creates URLs for list, create, retrieve, update, delete
router.register('programs', ProgramViewSet, basename='program')
router.register('applications', ApplicationViewSet)

# Define URL patterns, including both router-generated and custom endpoints
urlpatterns = [
    # Include all URLs generated by the router
    path('', include(router.urls)),
    
    # Authentication endpoints
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    # User profile endpoint
    path('users/me/', get_current_user, name='current-user'),
]
