name: DEV - Main Branch Mishmash Deployment

on:
  push:
    branches: [main]

  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev Server
      url: https://dev-mishmash.colab.duke.edu
    steps:
      - name: Set deployment timestamp
        run: echo "DEPLOYMENT_TIME=$(date -u)" >> $GITHUB_ENV


      - name: Connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/vcm/studyabroad
            git fetch origin
            git checkout main  # Switch to main branch
            git reset --hard origin/main  # Force sync to remote main branch
            git pull origin main

            
            # setup sentry token
            cat <<EOF > ./mishmash/frontend/.sentryclirc
            [auth]
            token=${{ secrets.SENTRY_AUTH_TOKEN }}
            EOF
            
            
            # Create .env file with all secret values.
            cat <<EOF > .env
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            EOF


            docker compose -f docker-compose.dev.yml down
            docker volume rm $(docker volume ls -q)
            docker compose -f docker-compose.dev.yml up -d --build
            echo "🔄 Checking container status..."
            docker compose ps
    

      - name: Discord success notification
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "DEV - Deployment Successful"
          description: "Containers started successfully at ${{ env.DEPLOYMENT_TIME }}"
          color: 0x00ff00  # Green color

      - name: Discord failure notification
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "DEV - Deployment Failed"
          description: "Container startup failed at ${{ env.DEPLOYMENT_TIME }}"
          color: 0xff0000  # Red color
